# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3250a1580f900632d7cc67082c7f098400ade25928e5303a1aaf10d0991f80562ba96c02f35cfe934c226c99e26f489122941ad0ac15a2934beac97b1c63cd40

test:
  secret_key_base: a0c55d9f8cea3b8ad24bf6d1ac4a1cf90fd9d6d01e5f1a17213a711ce2e0a6109837782d1e43a1c66f4b7a24a59edf6898585c8f95ac3e9e6e27547a86508ebc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
